import React, { useState } from 'react';
import { useSqlStore } from '../../../store/sqlStore';
import { Card, CardContent, CardHeader, CardTitle } from '../../../components/ui/Card';
import { Badge } from '../../../components/ui/Badge';
import { SqlExecutionLog, SqlOperationType } from '../../../types';
import { Activity, Clock, Database, CheckCircle2, XCircle, ArrowRight, Table as TableIcon, Trash2 } from 'lucide-react';
import { Button } from '../../../components/ui/Button';

export const SqlPlayground = () => {
  const { logs, clearLogs } = useSqlStore();
  const [selectedLog, setSelectedLog] = useState<SqlExecutionLog | null>(null);
  const [filter, setFilter] = useState<SqlOperationType | 'ALL'>('ALL');

  const filteredLogs = logs.filter(log => filter === 'ALL' || log.operation_type === filter);

  const getStatusColor = (status: SqlExecutionLog['execution_status']) => {
    switch (status) {
      case 'Success': return 'success';
      case 'Failed': return 'destructive';
      case 'Rollback': return 'warning';
      default: return 'default';
    }
  };

  const getOperationColor = (op: SqlOperationType) => {
    switch (op) {
      case 'INSERT': return 'bg-green-500/10 text-green-600 dark:text-green-400 border-green-200 dark:border-green-800';
      case 'UPDATE': return 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-200 dark:border-blue-800';
      case 'DELETE': return 'bg-red-500/10 text-red-600 dark:text-red-400 border-red-200 dark:border-red-800';
      case 'SELECT': return 'bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-200 dark:border-purple-800';
      default: return 'bg-gray-500/10 text-gray-600 dark:text-gray-400 border-gray-200 dark:border-gray-800';
    }
  };

  return (
    <div className="h-full flex flex-col space-y-4 animate-in fade-in duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">SQL Monitor & Playground</h2>
          <p className="text-muted-foreground mt-1">
            Real-time monitoring of database operations generated by UI interactions.
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={clearLogs} className="text-destructive">
          <Trash2 className="h-4 w-4 mr-2" />
          Clear Logs
        </Button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 min-h-0">
        {/* Left Column: Log History */}
        <Card className="col-span-1 flex flex-col h-full overflow-hidden">
          <CardHeader className="border-b pb-4 shrink-0">
            <CardTitle className="text-lg flex items-center justify-between">
              <span>Execution History</span>
              <Badge variant="secondary">{logs.length} queries</Badge>
            </CardTitle>
            <div className="flex flex-wrap gap-2 pt-4">
              {['ALL', 'INSERT', 'UPDATE', 'DELETE', 'SELECT'].map((f) => (
                <button
                  key={f}
                  onClick={() => setFilter(f as any)}
                  className={`px-3 py-1 text-xs rounded-full border transition-colors ${
                    filter === f 
                      ? 'bg-primary text-primary-foreground border-primary' 
                      : 'bg-background text-muted-foreground hover:bg-muted'
                  }`}
                >
                  {f}
                </button>
              ))}
            </div>
          </CardHeader>
          <CardContent className="flex-1 overflow-y-auto p-0 custom-scrollbar">
            {filteredLogs.length === 0 ? (
              <div className="p-8 text-center text-muted-foreground flex flex-col items-center justify-center h-full">
                <Database className="h-8 w-8 mb-2 opacity-20" />
                <p>No queries recorded yet.</p>
                <p className="text-xs mt-1">Interact with the UI to generate SQL.</p>
              </div>
            ) : (
              <div className="divide-y divide-border/50">
                {filteredLogs.map((log) => (
                  <div 
                    key={log.id} 
                    onClick={() => setSelectedLog(log)}
                    className={`p-4 cursor-pointer hover:bg-muted/50 transition-colors ${selectedLog?.id === log.id ? 'bg-muted border-l-2 border-primary' : ''}`}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-sm border ${getOperationColor(log.operation_type)}`}>
                        {log.operation_type}
                      </span>
                      <span className="text-xs text-muted-foreground">
                        {new Date(log.timestamp).toLocaleTimeString()}
                      </span>
                    </div>
                    <div className="flex items-center gap-2 mb-2">
                      <TableIcon className="h-4 w-4 text-muted-foreground" />
                      <span className="text-sm font-medium">{log.table_name}</span>
                    </div>
                    <p className="text-xs text-muted-foreground font-mono truncate">
                      {log.query}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Right Column: Execution Details */}
        <Card className="col-span-2 flex flex-col h-[calc(100vh-12rem)] overflow-hidden">
          {selectedLog ? (
            <div className="flex flex-col h-full overflow-y-auto custom-scrollbar">
              <CardHeader className="border-b bg-muted/20 shrink-0">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <span className={`text-xs font-bold px-2 py-1 rounded-sm border ${getOperationColor(selectedLog.operation_type)}`}>
                      {selectedLog.operation_type}
                    </span>
                    <CardTitle className="text-xl">Query Details</CardTitle>
                  </div>
                  <Badge variant={getStatusColor(selectedLog.execution_status)} className="flex items-center gap-1 px-3 py-1 text-sm">
                    {selectedLog.execution_status === 'Success' ? <CheckCircle2 className="h-4 w-4" /> : <XCircle className="h-4 w-4" />}
                    {selectedLog.execution_status}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="p-6 space-y-6">
                
                {/* Stats Grid */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  <div className="p-4 rounded-lg bg-background border flex flex-col">
                    <span className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <TableIcon className="h-3 w-3" /> Table Affected
                    </span>
                    <span className="font-semibold">{selectedLog.table_name}</span>
                  </div>
                  <div className="p-4 rounded-lg bg-background border flex flex-col">
                    <span className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <Activity className="h-3 w-3" /> Rows Affected
                    </span>
                    <span className="font-semibold">{selectedLog.rows_affected}</span>
                  </div>
                  <div className="p-4 rounded-lg bg-background border flex flex-col">
                    <span className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <Clock className="h-3 w-3" /> Execution Time
                    </span>
                    <span className="font-semibold">{selectedLog.execution_time_ms.toFixed(2)} ms</span>
                  </div>
                  <div className="p-4 rounded-lg bg-background border flex flex-col">
                    <span className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <Database className="h-3 w-3" /> Transaction
                    </span>
                    <span className="font-semibold">{selectedLog.transaction_status}</span>
                  </div>
                </div>

                {/* SQL Query Box */}
                <div>
                  <h3 className="text-sm font-medium mb-2">Executed SQL Statement</h3>
                  <div className="bg-[#1e1e2e] text-[#a6accd] p-4 rounded-lg font-mono text-sm overflow-x-auto shadow-inner border border-[#1e1e2e]/50">
                    <pre className="whitespace-pre-wrap">{selectedLog.query}</pre>
                  </div>
                </div>

                {/* Data Diff (if applicable) */}
                {(selectedLog.before_data || selectedLog.after_data) && (
                  <div>
                    <h3 className="text-sm font-medium mb-3">Data State Transformation</h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      {/* Before State */}
                      <div className="rounded-lg border bg-muted/10 overflow-hidden flex flex-col">
                        <div className="bg-muted px-4 py-2 border-b text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                          Before Execution
                        </div>
                        <div className="p-4 overflow-x-auto">
                          {selectedLog.before_data ? (
                            <pre className="text-xs font-mono text-red-500 dark:text-red-400">
                              {JSON.stringify(selectedLog.before_data, null, 2)}
                            </pre>
                          ) : (
                            <span className="text-xs text-muted-foreground italic">Null (New Record Inserted)</span>
                          )}
                        </div>
                      </div>
                      
                      {/* After State */}
                      <div className="rounded-lg border bg-muted/10 overflow-hidden flex flex-col">
                        <div className="bg-muted px-4 py-2 border-b text-xs font-semibold uppercase tracking-wider text-muted-foreground flex justify-between items-center">
                          <span>After Execution</span>
                          <ArrowRight className="h-4 w-4 text-green-500" />
                        </div>
                        <div className="p-4 overflow-x-auto">
                          {selectedLog.after_data ? (
                            <pre className="text-xs font-mono text-green-600 dark:text-green-400">
                              {JSON.stringify(selectedLog.after_data, null, 2)}
                            </pre>
                          ) : (
                            <span className="text-xs text-muted-foreground italic">Null (Record Deleted)</span>
                          )}
                        </div>
                      </div>
                    </div>
                  </div>
                )}
                
              </CardContent>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-muted-foreground p-8 text-center h-full">
              <Activity className="h-12 w-12 mb-4 opacity-20" />
              <h3 className="text-lg font-medium mb-2">No Query Selected</h3>
              <p>Select a query from the history panel to view detailed execution metrics, state transformations, and performance data.</p>
            </div>
          )}
        </Card>
      </div>
    </div>
  );
};
